[project]
name = "expanse-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiomysql>=0.3.2",
    "alembic>=1.18.4",
    "apscheduler>=3.11.2",
    "argon2-cffi>=25.1.0",
    "cryptography>=46.0.4",
    "fastapi-mail>=1.6.2",
    "fastapi-users[sqlalchemy]>=15.0.4",
    "fastapi[standard]>=0.128.4",
    "numpy>=2.2.6",
    "passlib>=1.7.4",
    "pillow>=12.2.0",
    "pydantic>=2.0",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.2.1",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.22",
    "redis>=7.4.0",
    "sqlalchemy>=2.0.46",
    "sqlmodel>=0.0.32",
    "uvicorn>=0.40.0",
]
